version: '3.8'

services:
  # container-1
  mysql8-server:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=Welcome#123
    volumes: 
      - mysqldata:/var/lib/mysql

volumes: 
  mysqldata: 