version: '3.8'

services: 
    flask-app:
      container_name: flask-app
      build:
        context: .
      ports: 
        - '5000:5000'

    redis-server:
      image: 'redis:latest'
      container_name: redis-server